services:
  quick-snip:
    build: .
    image: quick-snip:latest
    network_mode: bridge
    ports:
      - "8207:8000"
    volumes:
      - ./data:/app/uploads
      - ./data_out:/app/outputs
    restart: unless-stopped
