services:
  jasvccd:
    image: mythosaz/jasvccd:latest
    ports:
      - "8080:8000"
    volumes:
      - jas_data:/app/uploads
      - jas_out:/app/outputs
    restart: unless-stopped

volumes:
  jas_data:
  jas_out:
